import React from 'react';
import {Search,Plus,BookOpen,Bell,ChevronDown,Command} from 'lucide-react';
import {AxisId} from '../types/cogem';
const ENAP_LOGO_URL='https://www.gov.br/governodigital/pt-br/privacidade-e-seguranca/centro-de-excelencia-em-privacidade-e-seguranca/enap/imagens/logo-enap.png';
interface HeaderProps{activeTab:string;setActiveTab:(tab:string)=>void;onOpenNewAction:()=>void;globalSearch:string;setGlobalSearch:(val:string)=>void;selectedAxisId:AxisId|'all';setSelectedAxisId:(axis:AxisId|'all')=>void;onOpenAboutModal:()=>void}
export const Header:React.FC<HeaderProps>=({setActiveTab,onOpenNewAction,globalSearch,setGlobalSearch,setSelectedAxisId,onOpenAboutModal})=><header className="sticky top-0 z-40 h-[72px] bg-white/90 backdrop-blur-xl border-b border-[#e9e5ec]"><div className="h-full px-5 lg:px-7 flex items-center justify-between gap-4">
<button onClick={()=>{setActiveTab('dashboard');setSelectedAxisId('all')}} className="flex items-center gap-3 shrink-0 group"><div className="w-[72px] h-9 flex items-center justify-start overflow-hidden"><img src={ENAP_LOGO_URL} alt="Enap" className="w-[70px] h-auto object-contain" /></div><div className="hidden sm:block text-left"><div className="flex items-center gap-2"><span className="text-sm font-extrabold tracking-tight">COGEM Conecta</span><span className="px-2 py-0.5 rounded-full bg-[#f0ecff] text-[#6041e6] text-[9px] font-bold">WORKSPACE</span></div><span className="text-[10px] text-[#77717f]">Gestão estratégica e conhecimento</span></div></button>
<div className="flex-1 max-w-2xl hidden md:block"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-[#938d9b]"/><input value={globalSearch} onChange={e=>setGlobalSearch(e.target.value)} placeholder="Pesquisar ações, documentos, pessoas, siglas..." className="w-full h-10 pl-11 pr-20 rounded-xl bg-[#f7f6f8] border border-transparent focus:bg-white focus:border-[#d8cff7] focus:ring-4 focus:ring-[#6d4aff]/8 outline-none text-xs placeholder:text-[#9b96a2] transition-all"/><div className="absolute right-3 top-1/2 -translate-y-1/2 hidden lg:flex items-center gap-1 text-[10px] text-[#aaa4af]"><Command className="w-3 h-3"/>K</div></div></div>
<div className="flex items-center gap-2"><button onClick={onOpenAboutModal} className="hidden lg:flex items-center gap-2 h-9 px-3 rounded-xl text-[11px] font-semibold text-[#5d5863] hover:bg-[#f7f6f8]"><BookOpen className="w-3.5 h-3.5"/>Modelo</button><button onClick={onOpenNewAction} className="h-9 px-3.5 rounded-xl bg-[#6d4aff] hover:bg-[#5e3feb] text-white text-[11px] font-bold flex items-center gap-1.5 shadow-[0_6px_18px_rgba(109,74,255,.22)]"><Plus className="w-3.5 h-3.5"/><span className="hidden sm:inline">Nova ação</span></button><button className="w-9 h-9 rounded-xl border border-[#e9e5ec] bg-white flex items-center justify-center text-[#77717f]"><Bell className="w-4 h-4"/></button><button className="hidden sm:flex items-center gap-2 pl-1"><div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#c9e86a] to-[#27c7c9] flex items-center justify-center text-[10px] font-extrabold">DM</div><ChevronDown className="w-3 h-3 text-[#938d9b]"/></button></div>
</div></header>;